<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateDealsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('deals', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id')->nullable();
            $table->integer('client_id')->nullable();
            $table->integer('product_id')->nullable();
            $table->integer('deal_stage_id')->nullable();
            $table->string('name', 255)->nullable();
            $table->double('amount')->nullable();
            $table->nullableTimestamps();
            $table->softDeletes();

            $table->index('client_id', 'fk_deals_clients1_idx');
            $table->index('product_id', 'fk_deals_products1_idx');
            $table->index('deal_stage_id', 'fk_deals_deal_stages1_idx');
            $table->index('user_id', 'fk_deals_users1_idx');

            $table->foreign('client_id', 'fk_deals_clients1')
                ->references('id')
                ->on('clients')
                ->onDelete('NO ACTION')
                ->onUpdate('NO ACTION');

            $table->foreign('deal_stage_id', 'fk_deals_deal_stages1')
                ->references('id')
                ->on('deal_stages')
                ->onDelete('NO ACTION')
                ->onUpdate('NO ACTION');

            $table->foreign('product_id', 'fk_deals_products1')
                ->references('id')
                ->on('products')
                ->onDelete('NO ACTION')
                ->onUpdate('NO ACTION');

            $table->foreign('user_id', 'fk_deals_users1')
                ->references('id')
                ->on('users')
                ->onDelete('NO ACTION')
                ->onUpdate('NO ACTION');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('deals');
    }
}
