<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateDealNotesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('deal_notes', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id')->nullable();
            $table->integer('deal_id')->nullable();
            $table->longText('body')->nullable();
            $table->nullableTimestamps();

            $table->index('user_id', 'fk_deal_notes_users1_idx');
            $table->index('deal_id', 'fk_deal_notes_deals1_idx');

            $table->foreign('deal_id', 'fk_deal_notes_deals1')
                ->references('id')
                ->on('deals')
                ->onDelete('NO ACTION')
                ->onUpdate('NO ACTION');

            $table->foreign('user_id', 'fk_deal_notes_users1')
                ->references('id')
                ->on('users')
                ->onDelete('NO ACTION')
                ->onUpdate('NO ACTION');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('deal_notes');
    }
}
