<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateLeadsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('leads', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('company_id')->nullable();
            $table->integer('lead_class_id')->nullable();
            $table->string('first_name', 45)->nullable();
            $table->string('last_name', 45)->nullable();
            $table->string('country_code', 45)->nullable();
            $table->string('phone_number', 45)->nullable();
            $table->string('email', 100)->nullable();
            $table->nullableTimestamps();
            $table->softDeletes();

            $table->index('lead_class_id', 'fk_leads_lead_classes1_idx');
            $table->index('company_id', 'fk_leads_companies1_idx');

            $table->foreign('lead_class_id', 'fk_leads_lead_classes1')
                ->references('id')
                ->on('lead_classes')
                ->onDelete('NO ACTION')
                ->onUpdate('NO ACTION');

            $table->foreign('company_id', 'fk_leads_companies1')
                ->references('id')
                ->on('companies')
                ->onDelete('NO ACTION')
                ->onUpdate('NO ACTION');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('leads');
    }
}
