<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateRolePermissionTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('role_permission', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('permission_id')->nullable();
            $table->integer('role_id')->nullable();
            $table->nullableTimestamps();
            $table->softDeletes();

            $table->index('permission_id', 'fk_role_permission_permissions1_idx');
            $table->index('role_id', 'fk_role_permission_roles1_idx');

            $table->foreign('permission_id', 'fk_role_permission_permissions1')
                ->references('id')
                ->on('permissions')
                ->onDelete('NO ACTION')
                ->onUpdate('NO ACTION');

            $table->foreign('role_id', 'fk_role_permission_roles1')
                ->references('id')
                ->on('roles')
                ->onDelete('NO ACTION')
                ->onUpdate('NO ACTION');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('role_permission');
    }
}
