<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('company_id')->nullable();
            $table->string('first_name', 45)->nullable();
            $table->string('last_name', 45)->nullable();
            $table->string('email', 255)->nullable();
            $table->dateTime('email_verified_at')->nullable();
            $table->string('phone', 45)->nullable();
            $table->string('remember_token', 255)->nullable();
            $table->string('password', 255)->nullable();
            $table->nullableTimestamps();
            $table->softDeletes();

            $table->unique('email', 'email_UNIQUE');
            $table->index('company_id', 'fk_users_companies_idx');

            $table->foreign('company_id', 'fk_users_companies')
                ->references('id')
                ->on('companies')
                ->onDelete('NO ACTION')
                ->onUpdate('NO ACTION');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('users');
    }
}
